### ISSUE TITLE
Progressive rendering step

### ISSUE THREAD

**Issue by jinnan-chen** [sail-sg/GP-Nerf#2]
Hi Xiangyu,
Thanks for inspiring work! I am a little confused about the Progressive Rendering step. Does it exist only in the test time since with code demo_render.py? It seems that in the training Base_Render.py, the only function to speed up the rendering process is to mask out the sampled points with less than 2 observations. Am I missing something? Thanks!

**Comment by yoyomimi** [comment]
Hi, yes, the progressive rendering step is only for the test time. Because for training steps, we can sample rays for each training image, but for testing, we need to process all the rays if we don't use the progressive rendering step. The progressive step is more effective for the testing process.
Hope this can help you.

**Comment by jinnan-chen** [comment]
Thanks for replying!
